name: Versioning

on:
  release:
    types: [created, published, edited]

permissions:
  contents: write

jobs:
  actions-tagger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update release tags
        uses: Actions-R-Us/actions-tagger@latest
        with:
          publish_latest_tag: true
